from __future__ import annotations

from typing import Protocol


class ScaleReaderProtocol(Protocol):
    @property
    def connected(self) -> bool: ...

    def read_mass(self) -> float | None: ...

    def tare(self) -> bool: ...

    def zero(self) -> bool: ...

    def close(self) -> None: ...


class FurnaceReaderProtocol(Protocol):
    @property
    def connected(self) -> bool: ...

    def read_pv(self) -> float | None: ...

    def read_sv(self) -> float | None: ...

    def read_temperatures(self) -> tuple[float | None, float | None]: ...

    def close(self) -> None: ...
