from __future__ import annotations

DEFAULTS: dict[str, object] = {
    "scale.enabled": True,
    "scale.baudrate": 9600,
    "scale.timeout": 1.0,
    "scale.mode": "continuous",
    "scale.request_command": "P\r\n",
    "scale.p1_polling_enabled": False,
    "scale.p1_poll_interval_sec": 0.1,
    "furnace.enabled": True,
    "furnace.baudrate": 9600,
    "furnace.bytesize": 7,
    "furnace.parity": "E",
    "furnace.stopbits": 1,
    "furnace.timeout": 1.0,
    "furnace.slave_id": 1,
    "furnace.register_pv": 90,
    "furnace.register_sv": 91,
    "furnace.scale_factor": 0.1,
    "furnace.register_mode_pv": 4,
    "furnace.register_mode_sv": 4,
    "furnace.driver": "dk518",
    "furnace.access_mode": "read_only",
    "furnace.window_enabled": False,
    "furnace.window_period_ms": 1000,
    "furnace.window_open_ms": 120,
    "furnace.window_offset_ms": 0,
    "furnace.experimental_write_enabled": False,
    "furnace.input_type_code": 0,
    "furnace.input_type_name": "K",
    "furnace.high_limit": 1200.0,
    "furnace.high_alarm": 999.9,
    "furnace.low_alarm": 999.9,
    "furnace.pid_p": 10.0,
    "furnace.pid_t": 8.0,
    "furnace.ctrl_mode": 3,
    "furnace.output_high_limit": 100.0,
    "furnace.display_decimals": 2,
    "furnace.sensor_correction": 0.0,
    "furnace.opt_code": 8,
    "furnace.run_code": 27,
    "furnace.alarm_output_code": 3333,
    "furnace.m5_value": 420.0,
    "app.poll_interval_sec": 1.0,
    "app.max_points_on_plot": 500,
    "app.auto_detect_ports": True,
    "app.test_mode": False,
    "app.test_mode_scope": "all",
    "app.autosave_settings": False,
    "app.enable_file_logging": False,
    "app.start_maximized": False,
    "app.fullscreen": False,
    "app.font_scale": 1.05,
    "app.theme": "dark",
    "app.csv_path": "data/measurements.csv",
    "app.log_path": "logs/app.log",
}

SETTINGS_SECTIONS: list[
    tuple[str, list[tuple[str, str, str, str, tuple[str, ...] | None]]]
] = [
    (
        "Весы",
        [
            ("scale.enabled", "Использовать весы", "bool", "Включает опрос лабораторных весов.", None),
            ("scale.baudrate", "Скорость связи", "entry", "Для ускоренного режима обычно 9600 бод, если весы настроены так же.", None),
            ("scale.timeout", "Таймаут, сек", "entry", "Сколько ждать строку от весов перед повтором.", None),
            ("scale.mode", "Режим чтения", "combo", "Для P2 Con лучше continuous. auto оставляет резервный опрос, если поток пропадёт.", ("auto", "continuous", "poll")),
            ("scale.request_command", "Команда опроса", "entry", "Обычно P\\r\\n. Тара и ноль задаются отдельными кнопками.", None),
            ("scale.p1_polling_enabled", "Режим P1 Prt", "bool", "Принудительно читать весы по команде P в режиме P1 Prt.", None),
            ("scale.p1_poll_interval_sec", "Тайминг опроса P1, сек", "entry", "Интервал между командными опросами в P1 Prt. По умолчанию быстрый.", None),
        ],
    ),
    (
        "Печь",
        [
            ("furnace.enabled", "Использовать печь", "bool", "Включает чтение температуры по Modbus RTU.", None),
            ("furnace.driver", "Драйвер печи", "combo", "Выберите профиль dk518 или ручной Modbus-режим для другого контроллера.", ("dk518", "modbus")),
            ("furnace.baudrate", "Скорость связи", "entry", "Обычно 9600 бод для USB-RS485 адаптера.", None),
            ("furnace.bytesize", "Биты данных", "combo", "Для подтверждённого профиля DK518 используется 7 бит данных.", ("7", "8")),
            ("furnace.parity", "Чётность", "combo", "Для подтверждённого профиля DK518 используется E.", ("N", "E", "O")),
            ("furnace.stopbits", "Стоп-биты", "combo", "Обычно 1.", ("1", "1.5", "2")),
            ("furnace.timeout", "Таймаут, сек", "entry", "Сколько ждать ответ по Modbus RTU.", None),
            ("furnace.slave_id", "Адрес устройства", "entry", "Modbus slave ID контроллера.", None),
            ("furnace.access_mode", "Режим доступа", "combo", "read_only для пассивного слушателя и безопасного режима. active_modbus для активного опроса универсального Modbus-устройства.", ("read_only", "active_modbus")),
            ("furnace.register_pv", "Регистр температуры камеры", "entry", "Подтверждённый адрес для температуры внутри камеры: 90 / 0x005A.", None),
            ("furnace.register_sv", "Регистр температуры термопары", "entry", "Подтверждённый адрес для термопары: 91 / 0x005B.", None),
            ("furnace.register_mode_pv", "Функция PV", "combo", "Как читать регистр температуры камеры: 3 = holding, 4 = input.", ("3", "4")),
            ("furnace.register_mode_sv", "Функция SV", "combo", "Как читать регистр термопары: 3 = holding, 4 = input.", ("3", "4")),
            ("furnace.scale_factor", "Масштаб температуры", "entry", "Например 0.1, если 253 означает 25.3 °C.", None),
            ("furnace.input_type_code", "Код входа датчика", "entry", "С панели MCGS сейчас считан код 0.", None),
            ("furnace.input_type_name", "Тип датчика", "combo", "С панели MCGS сейчас считан тип K.", ("K", "S", "R", "T", "E", "J", "B", "N", "WRe3-25", "WRe5-26", "Cu50", "Pt100")),
            ("furnace.high_limit", "Верхний предел", "entry", "С панели MCGS: HIAL = 1200.", None),
            ("furnace.high_alarm", "Верхняя тревога", "entry", "С панели MCGS: DHAL = 999.9.", None),
            ("furnace.low_alarm", "Нижняя тревога", "entry", "С панели MCGS: DLAL = 999.9.", None),
            ("furnace.pid_p", "PID: P", "entry", "С панели MCGS: P = 10.", None),
            ("furnace.pid_t", "PID: T", "entry", "С панели MCGS: T = 8.", None),
            ("furnace.ctrl_mode", "Режим CTRL", "entry", "С панели MCGS: CTRL = 3.", None),
            ("furnace.output_high_limit", "Предел выхода OPH", "entry", "С панели MCGS: OPH = 100.", None),
            ("furnace.display_decimals", "Разрядность DL", "entry", "С панели MCGS: DL = 2.", None),
            ("furnace.sensor_correction", "Коррекция SC", "entry", "С панели MCGS: SC = 0.", None),
            ("furnace.opt_code", "Код OPT", "entry", "С панели MCGS: OPT = 8.", None),
            ("furnace.run_code", "Код RUN", "entry", "С панели MCGS: RUN = 27.", None),
            ("furnace.alarm_output_code", "Код ALOP", "entry", "С панели MCGS: ALOP = 3333.", None),
            ("furnace.m5_value", "Параметр M5", "entry", "С панели MCGS: M5 = 420.", None),
        ],
    ),
    (
        "Приложение",
        [
            ("app.poll_interval_sec", "Интервал опроса, сек", "entry", "Как часто обновлять измерения и график.", None),
            ("app.max_points_on_plot", "Точек на графике", "entry", "Сколько последних точек держать на экране.", None),
            ("app.auto_detect_ports", "Автопоиск COM-портов", "bool", "При запуске программа пытается найти и назначить печь и весы по именам COM-устройств.", None),
            ("app.test_mode", "Тестовый режим", "bool", "Генерирует данные без реального оборудования.", None),
            ("app.test_mode_scope", "Что эмулировать", "combo", "Можно эмулировать только весы, только печь или оба устройства сразу.", ("all", "scale", "furnace")),
        ],
    ),
    (
        "Интерфейс и файлы",
        [
            ("app.theme", "Тема оформления", "combo", "Оформление окна программы.", ("dark", "light")),
            ("app.start_maximized", "Старт развернутым", "bool", "Рекомендуется включить для лабораторного ПК.", None),
            ("app.fullscreen", "Полный экран", "bool", "Если включено, окно откроется на весь экран.", None),
            ("app.csv_path", "Файл CSV", "entry", "Основной файл накопления измерений.", None),
            ("app.log_path", "Файл журнала", "entry", "Файл служебного журнала программы.", None),
            ("app.enable_file_logging", "Включить автологирование", "bool", "Записывать служебный журнал в файл на диске.", None),
        ],
    ),
]

TABLE_COLUMN_SPECS: tuple[tuple[str, str, int, str], ...] = (
    ("row_number", "№", 70, "center"),
    ("timestamp", "Время", 270, "w"),
    ("mass", "Масса, г", 130, "center"),
    ("pv", "Камера PV, °C", 150, "center"),
    ("sv", "Термопара SV, °C", 170, "center"),
)

TEST_MODE_SCOPE_LABELS: dict[str, str] = {
    "all": "Весы и печь",
    "scale": "Только весы",
    "furnace": "Только печь",
}
TEST_MODE_SCOPE_VALUES: tuple[str, ...] = tuple(TEST_MODE_SCOPE_LABELS.values())

TOOLTIP_DETAILS: dict[str, str] = {
    "scale.enabled": "Отключите этот параметр, если весы физически не подключены, чтобы программа не тратила время на лишние попытки чтения.",
    "scale.baudrate": "Если на весах уже включены P2 Con и For2, удобно использовать 9600 бод. Главное, чтобы скорость в программе совпадала с настройкой самих весов.",
    "scale.timeout": "Слишком маленький таймаут даст ложные ошибки, слишком большой замедлит опрос. Для начала обычно хватает 0.8-1.5 секунды.",
    "scale.mode": "Режим auto обычно самый удобный: программа сначала ждёт поток, а если поток не идёт, отправляет команду опроса сама.",
    "scale.request_command": "Меняйте это поле только если на реальном стенде выяснится, что весы требуют другую ASCII-команду. Обычно достаточно P\\r\\n.",
    "scale.p1_polling_enabled": "Включайте только если на самих весах выставлен режим P1 Prt. Тогда программа будет опрашивать их по команде, а не ждать непрерывный поток.",
    "scale.p1_poll_interval_sec": "Если хотите максимально частый опрос в P1 Prt, ставьте маленький интервал вроде 0.1-0.2 секунды. Слишком маленькое значение может только зря грузить COM-порт.",
    "furnace.enabled": "Если печь пока не подключена, можно временно снять галочку. Тогда программа продолжит работать только с весами.",
    "furnace.driver": "dk518 — готовый профиль для вашей печи: 9600 7E1, slave 1, чтение только. modbus — ручной активный профиль для другого контроллера и своих регистров.",
    "furnace.access_mode": "В режиме read_only программа только слушает линию и ничего не отправляет. В active_modbus программа сама опрашивает регистры печи.",
    "furnace.baudrate": "Если есть связь по USB-RS485, но нет ответа Modbus, проверьте baudrate одним из первых параметров вместе с parity и slave ID.",
    "furnace.bytesize": "У большинства контроллеров используется 8 бит данных. Меняйте только если это явно указано в документации контроллера.",
    "furnace.parity": "Для Modbus RTU часто критично совпадение parity. Если N не работает, проверьте в документации варианты E или O.",
    "furnace.stopbits": "Обычно используется 1 стоп-бит. Несовпадение этого параметра тоже может полностью ломать обмен по Modbus.",
    "furnace.timeout": "Если контроллер отвечает медленно, попробуйте увеличить таймаут до 1.5-2.0 секунды, чтобы исключить ложные таймауты.",
    "furnace.slave_id": "Это адрес Modbus-устройства. Если контроллер на шине не один, у каждого устройства должен быть свой адрес.",
    "furnace.register_pv": "Для текущего профиля DK518 здесь подтверждён адрес 90 (0x005A): температура внутри камеры.",
    "furnace.register_sv": "Для текущего профиля DK518 здесь подтверждён адрес 91 (0x005B): температура термопары.",
    "furnace.register_mode_pv": "Для универсального Modbus-контроллера выберите тип регистра: 3 = holding register, 4 = input register.",
    "furnace.register_mode_sv": "Для универсального Modbus-контроллера выберите тип регистра: 3 = holding register, 4 = input register.",
    "furnace.scale_factor": "Если регистр возвращает, например, 253 вместо 25.3 °C, задайте коэффициент 0.1. Если приходит 2530, может понадобиться 0.01.",
    "furnace.input_type_code": "На панели MCGS видно INP = 0, а по таблице типов это K. Это справочный параметр: для Modbus-обмена он сам по себе не задаёт адреса регистров.",
    "furnace.input_type_name": "Сейчас с панели видно, что датчик настроен как термопара K. Если на реальном контроллере тип сменят, обновите это поле для наглядности в проекте.",
    "furnace.high_limit": "Сейчас на панели видно HIAL = 1200. Полезно как ориентир верхнего диапазона, но на чтение Modbus напрямую не влияет.",
    "furnace.high_alarm": "Сейчас на панели видно DHAL = 999.9. Это справочный порог аварии.",
    "furnace.low_alarm": "Сейчас на панели видно DLAL = 999.9. Это справочный порог аварии.",
    "furnace.pid_p": "Сейчас на панели видно P = 10. Поле справочное, чтобы держать под рукой текущую настройку контура.",
    "furnace.pid_t": "Сейчас на панели видно T = 8. Поле справочное, без записи в контроллер.",
    "furnace.ctrl_mode": "Сейчас на панели видно CTRL = 3. Пока трактуем как паспортную настройку контроллера.",
    "furnace.output_high_limit": "Сейчас на панели видно OPH = 100. Это верхний предел выхода контроллера.",
    "furnace.display_decimals": "Сейчас на панели видно DL = 2. Может помочь при подборе scale_factor и понимании формата отображения.",
    "furnace.sensor_correction": "Сейчас на панели видно SC = 0. Это коррекция датчика/смещение.",
    "furnace.opt_code": "Сейчас на панели видно OPT = 8. Поле оставлено как справочный код конфигурации.",
    "furnace.run_code": "Сейчас на панели видно RUN = 27. Поле оставлено как справочный код конфигурации.",
    "furnace.alarm_output_code": "Сейчас на панели видно ALOP = 3333. Поле оставлено как справочный код конфигурации.",
    "furnace.m5_value": "Сейчас на панели видно M5 = 420. Пока используем как паспортное значение, без попыток трактовать жёстко.",
    "app.auto_detect_ports": "Если галочка включена, программа при старте обновляет список COM-портов и пытается сама назначить печь и весы по описанию USB-адаптеров.",
    "app.poll_interval_sec": "Для большинства задач 1 секунда удобно и достаточно. Уменьшайте интервал только если действительно нужна более частая запись.",
    "app.max_points_on_plot": "Чем больше точек, тем длиннее история на экране, но тем тяжелее перерисовка графика на слабом ноутбуке.",
    "app.test_mode": "Полезно для проверки интерфейса дома без оборудования: программа будет сама генерировать массу и температуру.",
    "app.autosave_settings": "Когда автосохранение включено, корректные изменения применяются и записываются в config.yaml сразу. Если поле введено не полностью, сохранение подождёт валидного значения.",
    "app.enable_file_logging": "Когда эта галочка выключена, программа пишет сообщения только в окно журнала и в консоль. Файл на диске не создаётся.",
    "app.theme": "Переключайте тему под освещение лаборатории. Светлая удобнее для печати скриншотов, тёмная часто комфортнее при длительной работе.",
    "app.start_maximized": "Рекомендуется оставить включённым для лабораторного ПК, чтобы все крупные элементы были сразу хорошо видны.",
    "app.fullscreen": "Используйте только если хотите режим без рамок окна. Для обычной работы чаще удобнее просто развёрнутое окно.",
    "app.test_mode_scope": "Можно включить эмуляцию только весов, только печи или сразу обоих устройств. Это удобно для проверки интерфейса и логики без полного стенда.",
    "app.csv_path": "Это основной файл накопления измерений. Убедитесь, что папка доступна на запись и не находится в защищённом системном каталоге.",
    "app.log_path": "Если программа ведёт себя нестабильно, этот файл помогает понять причину. Логи удобно прикладывать при разборе ошибок.",
    "app.font_scale": "Масштаб шрифта интерфейса. Увеличивайте, если на экране много мелкого текста. После резкого увеличения шрифта лучше перезапустить программу.",
}
